# Generated by Django 4.2.7 on 2023-11-04 20:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("video_url", models.URLField()),
                ("downloaded_video_path", models.FileField(upload_to="videos/")),
                (
                    "downloaded_captions_path",
                    models.FileField(blank=True, null=True, upload_to="captions/"),
                ),
                (
                    "downloaded_transcript_path",
                    models.FileField(blank=True, null=True, upload_to="transcripts/"),
                ),
            ],
        ),
    ]
