# Generated by Django 4.2.7 on 2023-11-04 20:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video_downloader", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="extracted_audio_path",
            field=models.FileField(blank=True, null=True, upload_to="audios/"),
        ),
        migrations.AddField(
            model_name="video",
            name="extracted_transcript_path",
            field=models.FileField(blank=True, null=True, upload_to="extracts/"),
        ),
    ]
